# Generated by Django 5.0.1 on 2024-01-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_availabilitymessage_availability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitymessage',
            name='availability',
            field=models.CharField(max_length=256),
        ),
    ]
